language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - './node_modules/.bin/ava'

after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'